SELECT AP.MATRICULA_PACIENTE,CONVERT(CHAR(5), AH.HORA, 14) AS HORA, AH.FLAG_HORA, 
 AP.NOME_PACIENTE, AU.DESCRICAO,
 AP.TELEFONE_PACIENTE, AC.RAZAO, CONVERT(CHAR(10),AC.OBSERVACAO,103) AS OBSERVACAO, 
 AE.DESC_ESPECIALIDADE, CONVERT(CHAR(10),AC.DATA_CONSULTA, 103) AS DATA_CONSULTA,
 'junta' = CASE 
 WHEN AM2.NOME_MEDICO IS NOT NULL AND AM3.NOME_MEDICO IS NOT NULL THEN 
 left(AM1.NOME_MEDICO,15)+'--'+left(AM2.NOME_MEDICO,15)+'--'+left(AM3.NOME_MEDICO,15)+'--'+upper(desc_especialidade) 
 WHEN AM2.NOME_MEDICO IS NOT NULL  AND AM3.NOME_MEDICO IS NULL THEN 
 left(AM1.NOME_MEDICO,15)+'--'+left(AM2.NOME_MEDICO,15)+'--'+upper(desc_especialidade) 
 WHEN AM2.NOME_MEDICO IS NULL  AND AM3.NOME_MEDICO IS NULL THEN 
 left(AM1.NOME_MEDICO,15)+'--'+upper(desc_especialidade)
	END
	FROM AG_CONSULTA AC
 	INNER JOIN AG_PACIENTE AP
	ON AP.ID_PACIENTE = AC.ID_PACIENTE
	INNER JOIN AG_UNIDADE AU
	ON AU.ID_UNIDADE = AP.ID_UNIDADE
	INNER JOIN AG_HORA AH 
	ON AH.ID_HORA = AC.ID_HORA 
	INNER JOIN AG_JUNTA AJ 
	ON AJ.ID_JUNTA = AC.ID_JUNTA 
	INNER JOIN AG_MEDICO AM1 
	ON AM1.ID_MEDICO = AJ.MEDICO1 
	LEFT JOIN AG_MEDICO AM2 
	ON AM2.ID_MEDICO = AJ.MEDICO2 
	LEFT JOIN AG_MEDICO AM3 
	ON AM3.ID_MEDICO = AJ.MEDICO3 
	INNER JOIN AG_ESPECIALIDADE AE 
	ON AE.ID_ESPECIALIDADE = AJ.ID_ESPECIALIDADE  
	WHERE AP.MATRICULA_PACIENTE = '1111623' 