sp_helpindex 'acesso'
dbcc showcontig('acesso','PK__ACESSO__45943E77')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (acesso, '', 70)
go
sp_helpindex 'acessomaterial'
dbcc showcontig('acessomaterial','PK_ACESSOMATERIAL')
DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (acessomaterial, '', 70)
go
sp_helpindex 'ADMINISTRATIVOFINANCEIRO'
dbcc showcontig('ADMINISTRATIVOFINANCEIRO','PK_ACESSOMATERIAL')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (ADMINISTRATIVOFINANCEIRO, '', 70)
go
sp_helpindex 'agencia'
dbcc showcontig('agencia','PK__AGENCIA__4A8310C6')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (agencia, '', 70)
go
sp_helpindex 'ALERTAPATOLOGICO'
dbcc showcontig('ALERTAPATOLOGICO','PK__ALERTAPATOLOGICO__57A801BA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (ALERTAPATOLOGICO, '', 70)
go

sp_helpindex 'ANTIBIOTICO'
dbcc showcontig('ANTIBIOTICO','PK__ANTIBIOTICO__781FBE44')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (ANTIBIOTICO, '', 70)
go

sp_helpindex 'ATIVIDADE'
dbcc showcontig('ATIVIDADE','PK__ATIVIDADE__0B129727')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (ATIVIDADE, '', 70)
go

sp_helpindex 'ATIVIDADEACADEMICA'
dbcc showcontig('ATIVIDADEACADEMICA','PK__ATIVIDADEACADEMI__67201ACB')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (ATIVIDADEACADEMICA, '', 70)
go

sp_helpindex 'BRAZINDICE'
dbcc showcontig('BRAZINDICE','PK__BRAZINDICE__79F2F81D')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (BRAZINDICE, '', 70)
go

sp_helpindex 'CAPALOTE'
dbcc showcontig('CAPALOTE','PK_CAPALOTE')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (CAPALOTE, '', 70)
go

sp_helpindex 'CAPALOTEDETALHE'
dbcc showcontig('CAPALOTEDETALHE','PK_CAPALOTEDETALHE')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (CAPALOTEDETALHE, '', 70)
go

sp_helpindex 'CAPALOTEDETALHEGLOSA'
dbcc showcontig('CAPALOTEDETALHEGLOSA','PK_CAPALOTEDETALHEGLOSA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (CAPALOTEDETALHEGLOSA, '', 70)
go

sp_helpindex 'CATEGORIA_CID'
dbcc showcontig('CATEGORIA_CID','PK__CATEGORIA_CID__2E1BDC42')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (CATEGORIA_CID, '', 70)
go

sp_helpindex 'CategoriaProfissional'
dbcc showcontig('CategoriaProfissional','PK__CategoriaProfiss__3C69FB99')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (CategoriaProfissional, '', 70)
go

sp_helpindex 'CENTROCUSTO'
dbcc showcontig('CENTROCUSTO','PK_CENTROCUSTOS')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (CENTROCUSTO, '', 70)
go

sp_helpindex 'CLASSIFICACAO_DOENCA'
dbcc showcontig('CLASSIFICACAO_DOENCA','PK_CLASSIFICACAO_DOENCA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (CLASSIFICACAO_DOENCA, '', 70)
go

sp_helpindex 'CLASSIFICACAO_DOENCA_GRUPO'
dbcc showcontig('CLASSIFICACAO_DOENCA_GRUPO','PK_CLASSIFICACAO_DOENCA_GRUPO')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (CLASSIFICACAO_DOENCA_GRUPO, '', 70)
go

sp_helpindex 'CLIENTE'
dbcc showcontig('CLIENTE','PK__CLIENTE__440B1D61')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (CLIENTE, '', 70)
go

sp_helpindex 'CLINICA_VALIDACAO'
dbcc showcontig('CLINICA_VALIDACAO','PK_CLINICA_VALIDACAO')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (CLINICA_VALIDACAO, '', 70)
go

sp_helpindex 'CLINICAS'
dbcc showcontig('CLINICAS','PK_CLINICAS')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (CLINICAS, '', 70)
go

sp_helpindex 'COMORBIDADE'
dbcc showcontig('COMORBIDADE','PK_COMORBIDADE')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (COMORBIDADE, '', 70)
go

sp_helpindex 'ConsReg'
dbcc showcontig('ConsReg','PK__ConsReg__3CBF0154')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (ConsReg, '', 70)
go

sp_helpindex 'CONTACORRENTE'
dbcc showcontig('CONTACORRENTE','PK_CONTACORRENTE')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (CONTACORRENTE, '', 70)
go

sp_helpindex 'CONTASRECEBER'
dbcc showcontig('CONTASRECEBER','PK_CONTASRECEBER')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (CONTASRECEBER, '', 70)
go

sp_helpindex 'CONTASRECEBER_DETALHE_CONTAABERTA'
dbcc showcontig('CONTASRECEBER_DETALHE_CONTAABERTA','PK_CONTASRECEBER_DETALHE_CONTAABERTA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (CONTASRECEBER_DETALHE_CONTAABERTA, '', 70)
go

sp_helpindex 'CONTROLECATETER'
dbcc showcontig('CONTROLECATETER','PK_CONTROLECATETER')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (CONTROLECATETER, '', 70)
go

sp_helpindex 'CONVENIO'
dbcc showcontig('CONVENIO','PK__CONVENIO__44952D46')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (CONVENIO, '', 70)
go

sp_helpindex 'DATAS_FECHAMENTO_COBRANCA'
dbcc showcontig('DATAS_FECHAMENTO_COBRANCA','PK_DATAS_FECHAMENTO_COBRANCA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (DATAS_FECHAMENTO_COBRANCA, '', 70)
go

sp_helpindex 'DEFEITOPERCEBIDO'
dbcc showcontig('DEFEITOPERCEBIDO','PK__DEFEITOPERCEBIDO__78DED853')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (DEFEITOPERCEBIDO, '', 70)
go

sp_helpindex 'DEPENDENTES'
dbcc showcontig('DEPENDENTES','PK__DEPENDENTES__63D8CE75')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (DEPENDENTES, '', 70)
go

sp_helpindex 'DESPESA'
dbcc showcontig('DESPESA','PK_DESPESA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (DESPESA, '', 70)
go

sp_helpindex 'Despesa2003'
dbcc showcontig('Despesa2003','')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (Despesa2003, '', 70)
go

sp_helpindex 'DOLAR'
dbcc showcontig('DOLAR','PK__DOLAR__5CA1C101')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (DOLAR, '', 70)
go

sp_helpindex 'EMPRESASGRUPO'
dbcc showcontig('EMPRESASGRUPO','PK_EMPRESASGRUPO')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (EMPRESASGRUPO, '', 70)
go

sp_helpindex 'ENFERMAGEM'
dbcc showcontig('ENFERMAGEM','PK__ENFERMAGEM__13FDAE3A')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (ENFERMAGEM, '', 70)
go


sp_helpindex 'ENFINTERCORRENCIA'
dbcc showcontig('ENFINTERCORRENCIA','PK__ENFINTERCORRENCI__4F52B2DB')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (ENFINTERCORRENCIA, '', 70)
go


sp_helpindex 'ENFKITMATERIAL'
dbcc showcontig('ENFKITMATERIAL','PK__ENFKITMATERIAL__5046D714')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (ENFKITMATERIAL, '', 70)
go


sp_helpindex 'ENFMATERIAL'
dbcc showcontig('ENFMATERIAL','PK__ENFMATERIAL__2A962F78')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (ENFMATERIAL, '', 70)
go


sp_helpindex 'ENFMATERIALEXTRA'
dbcc showcontig('ENFMATERIALEXTRA','PK__ENFMATERIALEXTRA__513AFB4D')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (ENFMATERIALEXTRA, '', 70)
go


sp_helpindex 'ENFPARPROC'
dbcc showcontig('ENFPARPROC','PK_ENFPARPROC')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (ENFPARPROC, '', 70)
go


sp_helpindex 'ENTREGAFATURA'
dbcc showcontig('ENTREGAFATURA','PK__ENTREGAFATURA__53AD53A4')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (ENTREGAFATURA, '', 70)
go


sp_helpindex 'EQUIPAMENTO'
dbcc showcontig('EQUIPAMENTO','PK_EQUIPAMENTO')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (EQUIPAMENTO, '', 70)
go



sp_helpindex 'Especialidade'
dbcc showcontig('Especialidade','PK__Especialidade__44FF419A')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (Especialidade, '', 70)
go


sp_helpindex 'ESTADOCIVIL'
dbcc showcontig('ESTADOCIVIL','PK__ESTADOCIVIL__30F848ED')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (ESTADOCIVIL, '', 70)
go

sp_helpindex 'ESTORNOFATURA'
dbcc showcontig('ESTORNOFATURA','PK__ESTORNOFATURA__1A94D1D9')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (ESTORNOFATURA, '', 70)
go

sp_helpindex 'FATURAVALORTOTAL'
dbcc showcontig('FATURAVALORTOTAL','PK_FATURAVALORTOTAL  ')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (FATURAVALORTOTAL, '', 70)
go


sp_helpindex 'FEDERACAO'
dbcc showcontig('FEDERACAO','PK__FEDERACAO__31EC6D26')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (FEDERACAO, '', 70)
go

sp_helpindex 'FILIAL'
dbcc showcontig('FILIAL','PK__FILIAL__489AC854')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (FILIAL, '', 70)
go

sp_helpindex 'FILIALCONVENIO'
dbcc showcontig('FILIALCONVENIO','PK__FILIALCONVENIO__6D2D2E85')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (FILIALCONVENIO, '', 70)
go


sp_helpindex 'FILIALCONVENIO_SES'
dbcc showcontig('FILIALCONVENIO_SES','PK_FILIALCONVENIO_SES')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (FILIALCONVENIO_SES, '', 70)
go


sp_helpindex 'FILIALPARAMETROS'
dbcc showcontig('FILIALPARAMETROS','PK_FILIALPARAMETROS')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (FILIALPARAMETROS, '', 70)
go


sp_helpindex 'FILTROPROCEDIMENTO'
dbcc showcontig('FILTROPROCEDIMENTO','PK_FILTROPROCEDIMENTO')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (FILTROPROCEDIMENTO, '', 70)
go


sp_helpindex 'FONTEDESPESA'
dbcc showcontig('FONTEDESPESA','PK_FONTEDESPESA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (FONTEDESPESA, '', 70)
go


sp_helpindex 'FORMACAOPROFISSIONAL'
dbcc showcontig('FORMACAOPROFISSIONAL','PK__FORMACAOPROFISSI__6908633D')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (FORMACAOPROFISSIONAL, '', 70)
go



sp_helpindex 'FORMAPAGAMENTO'
dbcc showcontig('FORMAPAGAMENTO','PK__FORMAPAGAMENTO__625A9A57')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (FORMAPAGAMENTO, '', 70)
go

sp_helpindex 'FORNECEDOR'
dbcc showcontig('FORNECEDOR','PK_FORNECEDOR    ')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (FORNECEDOR, '', 70)
go

sp_helpindex 'GRUPO_MEDICO'
dbcc showcontig('GRUPO_MEDICO','PK_GRUPO_MEDICO')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (GRUPO_MEDICO, '', 70)
go

sp_helpindex 'GRUPO_MEDICO_HOSPITAL'
dbcc showcontig('GRUPO_MEDICO_HOSPITAL','PK_GRUPO_MEDICO_HOSPITAL')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (GRUPO_MEDICO_HOSPITAL, '', 70)
go

sp_helpindex 'GRUPOACESSO'
dbcc showcontig('GRUPOACESSO','PK__GRUPOACESSO__7913E27D')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (GRUPOACESSO, '', 70)
go

sp_helpindex 'GRUPODESPESA'
dbcc showcontig('GRUPODESPESA','PK__GRUPODESPESA__6442E2C9')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (GRUPODESPESA, '', 70)
go


sp_helpindex 'GRUPOEQUIPAMENTO'
dbcc showcontig('GRUPOEQUIPAMENTO','PK__GRUPOEQUIPAMENTO__5E8A0973')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (GRUPOEQUIPAMENTO, '', 70)
go


sp_helpindex 'GrupoInterc'
dbcc showcontig('GrupoInterc','PK__GrupoInterc__52AE4273z')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (GrupoInterc, '', 70)
go


sp_helpindex 'GrupoProc'
dbcc showcontig('GrupoProc','PK__GrupoProc__3D5E1FD2')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (GrupoProc, '', 70)
go

sp_helpindex 'GRUPORECEITA'
dbcc showcontig('GRUPORECEITA','PK__GRUPORECEITA__662B2B3B')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (GRUPORECEITA, '', 70)
go


sp_helpindex 'GRUPOSERVICO'
dbcc showcontig('GRUPOSERVICO','PK_GRUPOSERVICO')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (GRUPOSERVICO, '', 70)
go


sp_helpindex 'HONORARIO'
dbcc showcontig('HONORARIO','PK__HONORARIO__6F1576F7')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (HONORARIO, '', 70)
go


sp_helpindex 'HOSPITAL2'
dbcc showcontig('HOSPITAL2','PK__HOSPITAL__3627DDB5')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (HOSPITAL2, '', 70)
go

sp_helpindex 'HOSPITALAGENCIA'
dbcc showcontig('HOSPITALAGENCIA','PK__HOSPITALAGENCIA__4C413C06')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (HOSPITALAGENCIA, '', 70)
go

sp_helpindex 'INDICECORRECAO'
dbcc showcontig('INDICECORRECAO','PK_INDICECORRECAO')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (INDICECORRECAO, '', 70)
go

sp_helpindex 'INDICECORRECAOVALORES'
dbcc showcontig('INDICECORRECAOVALORES','PK_INDICECORRECAOVALORES')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (INDICECORRECAOVALORES, '', 70)
go

sp_helpindex 'INSTITUICAO'
dbcc showcontig('INSTITUICAO','PK__INSTITUICAO__0DEF03D2')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (INSTITUICAO, '', 70)
go

sp_helpindex 'ITEMDESPESA'
dbcc showcontig('ITEMDESPESA','PK_ITEMDESPESA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (ITEMDESPESA, '', 70)
go

sp_helpindex 'ITEMRECEITA'
dbcc showcontig('ITEMRECEITA','PK_ITEMRECEITA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (ITEMRECEITA, '', 70)
go

sp_helpindex 'JUSTIFICATIVA_ALTA'
dbcc showcontig('JUSTIFICATIVA_ALTA','PK_JUSTIFICATIVA_ALTA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (JUSTIFICATIVA_ALTA, '', 70)
go

sp_helpindex 'ka_manutencao'
dbcc showcontig('ka_manutencao','PK__ka_manutencao__5E0BB1DD')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (ka_manutencao, '', 70)
go

sp_helpindex 'KITMALA'
dbcc showcontig('KITMALA','KITMALA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (KITMALA, '', 70)
go

sp_helpindex 'KITMALAMATERIAL'
dbcc showcontig('KITMALAMATERIAL','PK_KITMALAMATERIAL')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (KITMALAMATERIAL, '', 70)
go

sp_helpindex 'KITMATERIAL'
dbcc showcontig('KITMATERIAL','PK__KITMATERIAL__33AA9866')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (KITMATERIAL, '', 70)
go

sp_helpindex 'KITMATERIAL_AUX'
dbcc showcontig('KITMATERIAL_AUX','PK__KITMATERIAL_AUX__5D6BC808')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (KITMATERIAL_AUX, '', 70)
go

sp_helpindex 'CobrancaFaturaAgrupadaOLD'
dbcc showcontig('CobrancaFaturaAgrupadaOLD','')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (CobrancaFaturaAgrupadaOLD, '', 70)
go

sp_helpindex 'CobrancaFaturaUnicaOLD'
dbcc showcontig('CobrancaFaturaUnicaOLD','')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (CobrancaFaturaUnicaOLD, '', 70)
go

sp_helpindex 'CobrancaSamaritanoOLD'
dbcc showcontig('CobrancaSamaritanoOLD','')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (CobrancaSamaritanoOLD, '', 70)
go


sp_helpindex 'LOCALACESSO'
dbcc showcontig('LOCALACESSO','PK__LOCALACESSO__3FDB6521')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (LOCALACESSO, '', 70)
go

sp_helpindex 'LOCALINTERNACAO'
dbcc showcontig('LOCALINTERNACAO','PK__LOCALINTERNACAO__70099B30')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (LOCALINTERNACAO, '', 70)
go

sp_helpindex 'LOGONUSUARIO'
dbcc showcontig('LOGONUSUARIO','PK__LOGONUSUARIO__6F7569AA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (LOGONUSUARIO, '', 70)
go
sp_helpindex 'MALAS'
dbcc showcontig('MALAS','PK_MALAS')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (MALAS, '', 70)
go
sp_helpindex 'MARCA'
dbcc showcontig('MARCA','PK_MARCA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (MARCA, '', 70)
go
sp_helpindex 'MARCAEQUIPAMENTO'
dbcc showcontig('MARCAEQUIPAMENTO','PK__MARCAEQUIPAMENTO__79D2FC8C')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (MARCAEQUIPAMENTO, '', 70)
go
sp_helpindex 'MATERIAL'
dbcc showcontig('MATERIAL','PK__MATERIAL__681373AD')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (MATERIAL, '', 70)
go
/*sp_helpindex 'MENSAGEM_CONTATO'
dbcc showcontig('MENSAGEM_CONTATO','PK__LOGONUSUARIO__6F7569AA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (MENSAGEM_CONTATO, '', 70)*/
go
sp_helpindex 'MENSAGEM_SISTEMA'
dbcc showcontig('MENSAGEM_SISTEMA','PK_MENSAGEM_SISTEMA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (MENSAGEM_SISTEMA, '', 70)
go
sp_helpindex 'MODELOEQUIPAMENTO'
dbcc showcontig('MODELOEQUIPAMENTO','PK__MODELOEQUIPAMENT__7AC720C5')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (MODELOEQUIPAMENTO, '', 70)
go
sp_helpindex 'MOTIVO_CRONICOS'
dbcc showcontig('MOTIVO_CRONICOS','PK_MOTIVO_CRONICOS')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (MOTIVO_CRONICOS, '', 70)
go
sp_helpindex 'MOTIVO_NAO_REALIZADO'
dbcc showcontig('MOTIVO_NAO_REALIZADO','PK_MOTIVO_NAO_REALIZADO')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (MOTIVO_NAO_REALIZADO, '', 70)
go
sp_helpindex 'MotivoAtraso'
dbcc showcontig('MotivoAtraso','PK__MotivoAtraso__34C8D9D1')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (MotivoAtraso, '', 70)
go
sp_helpindex 'LOGONUSUARIO'
dbcc showcontig('LOGONUSUARIO','PK__LOGONUSUARIO__6F7569AA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (LOGONUSUARIO, '', 70)
go
sp_helpindex 'LOGONUSUARIO'
dbcc showcontig('LOGONUSUARIO','PK__LOGONUSUARIO__6F7569AA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (LOGONUSUARIO, '', 70)
go
sp_helpindex 'LOGONUSUARIO'
dbcc showcontig('LOGONUSUARIO','PK__LOGONUSUARIO__6F7569AA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (LOGONUSUARIO, '', 70)
go
sp_helpindex 'LOGONUSUARIO'
dbcc showcontig('LOGONUSUARIO','PK__LOGONUSUARIO__6F7569AA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (LOGONUSUARIO, '', 70)
go
sp_helpindex 'LOGONUSUARIO'
dbcc showcontig('LOGONUSUARIO','PK__LOGONUSUARIO__6F7569AA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (LOGONUSUARIO, '', 70)
go
sp_helpindex 'LOGONUSUARIO'
dbcc showcontig('LOGONUSUARIO','PK__LOGONUSUARIO__6F7569AA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (LOGONUSUARIO, '', 70)
go
sp_helpindex 'LOGONUSUARIO'
dbcc showcontig('LOGONUSUARIO','PK__LOGONUSUARIO__6F7569AA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (LOGONUSUARIO, '', 70)
go
sp_helpindex 'LOGONUSUARIO'
dbcc showcontig('LOGONUSUARIO','PK__LOGONUSUARIO__6F7569AA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (LOGONUSUARIO, '', 70)
go
sp_helpindex 'LOGONUSUARIO'
dbcc showcontig('LOGONUSUARIO','PK__LOGONUSUARIO__6F7569AA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (LOGONUSUARIO, '', 70)
go
sp_helpindex 'LOGONUSUARIO'
dbcc showcontig('LOGONUSUARIO','PK__LOGONUSUARIO__6F7569AA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (LOGONUSUARIO, '', 70)
go
sp_helpindex 'LOGONUSUARIO'
dbcc showcontig('LOGONUSUARIO','PK__LOGONUSUARIO__6F7569AA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (LOGONUSUARIO, '', 70)
go
sp_helpindex 'LOGONUSUARIO'
dbcc showcontig('LOGONUSUARIO','PK__LOGONUSUARIO__6F7569AA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (LOGONUSUARIO, '', 70)
go
sp_helpindex 'LOGONUSUARIO'
dbcc showcontig('LOGONUSUARIO','PK__LOGONUSUARIO__6F7569AA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (LOGONUSUARIO, '', 70)
go
sp_helpindex 'LOGONUSUARIO'
dbcc showcontig('LOGONUSUARIO','PK__LOGONUSUARIO__6F7569AA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (LOGONUSUARIO, '', 70)
go
sp_helpindex 'LOGONUSUARIO'
dbcc showcontig('LOGONUSUARIO','PK__LOGONUSUARIO__6F7569AA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (LOGONUSUARIO, '', 70)
go
sp_helpindex 'LOGONUSUARIO'
dbcc showcontig('LOGONUSUARIO','PK__LOGONUSUARIO__6F7569AA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (LOGONUSUARIO, '', 70)
go
sp_helpindex 'LOGONUSUARIO'
dbcc showcontig('LOGONUSUARIO','PK__LOGONUSUARIO__6F7569AA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (LOGONUSUARIO, '', 70)
go
sp_helpindex 'LOGONUSUARIO'
dbcc showcontig('LOGONUSUARIO','PK__LOGONUSUARIO__6F7569AA')
--DBCC DBREINDEX (clinicas, 'PK_CLINICAS', 70)
DBCC DBREINDEX (LOGONUSUARIO, '', 70)
go
